#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub enum Token {
    Identifier { value: String },
    Number { value: String },
    String { value: String },
    Bool { value: String },
    Plus,
    Minus,
    RSlash,
    Star,
    Dot,
    Comma,
    Colon,
    SemiColon,
    And,
    Or,
    Not,
    Equal,
    EqualEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    RArrow,
    Funk,
    Let,
    If,
    Else,
    While,
    For,
}
